import 'package:mediapp/consts/consts.dart';

class AppStrings {
  static String appname = "Mediapp",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow = "Sign up now and exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgotpassword = "Forgot Password?",
      login = "Login",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      search = "Search doctor",
      signup = "Signup",
      welcome = "Welcome",
      alreadyHaveAccount = "Already have an account?",
      dontHaveAccount = "Don't have an account?",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidney = "Kidney",
      changePassword = "Change Password",
      termsConditions = "Terms & Conditions",
      signout = "Signout";
}
