// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsTF_BvLqYOm7Jxrl4qjAZiZlPduvkPo',
    appId: '1:566708733464:web:5bc93affa5b6bae500a56d',
    messagingSenderId: '566708733464',
    projectId: 'mediapp-50c07',
    authDomain: 'mediapp-50c07.firebaseapp.com',
    storageBucket: 'mediapp-50c07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhrEPnw0r0L1wNpCoq98vLlhwxW-1DYj8',
    appId: '1:566708733464:android:91e189f1bd71f22400a56d',
    messagingSenderId: '566708733464',
    projectId: 'mediapp-50c07',
    storageBucket: 'mediapp-50c07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6NB45jyTW8Wqh0usEBDxeyCHAbxfiwnY',
    appId: '1:566708733464:ios:4c0816bd64baa4c000a56d',
    messagingSenderId: '566708733464',
    projectId: 'mediapp-50c07',
    storageBucket: 'mediapp-50c07.appspot.com',
    iosBundleId: 'com.example.mediapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6NB45jyTW8Wqh0usEBDxeyCHAbxfiwnY',
    appId: '1:566708733464:ios:7e073e7d2e48de5300a56d',
    messagingSenderId: '566708733464',
    projectId: 'mediapp-50c07',
    storageBucket: 'mediapp-50c07.appspot.com',
    iosBundleId: 'com.example.mediapp.RunnerTests',
  );
}
